name: Generate Release

on:
  push:
    branches:
      - main
      - release/1.x
  workflow_dispatch:

concurrency: release

permissions:
  contents: write
  issues: write
  checks: write

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Install system-wide LibSodium
        run: sudo apt-get install -y libsodium-dev

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Maven Central
        env:
          GPG_TTY: ${{ runner.tty }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew publish publishToMavenCentralPortal
        continue-on-error: true

      - name: explore
        run: ls -alh lib/build
        continue-on-error: true

      - name: explore2
        run: ls -alh lib/build/libs
        continue-on-error: true

      - name: explore3
        run: ls -alh lib/build/distributions
        continue-on-error: true

      - name: explore4
        run: ls -alh lib/build/repos/bundles/io/github/hashmapsdata2value/hmd2v-lib
        continue-on-error: true

      - name: Merge Release -> Trunk
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f
        if: github.ref == 'refs/heads/release/1.x'
        with:
          type: now
          from_branch: release/1.x
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
